import { Service, ServiceDetail, Project, Testimonial, BlogPost, NavLink, Stat } from "@/types";
import {
  INTERVENTION_AREA_LABEL,
  INTERVENTION_BASE_CITY,
  INTERVENTION_LOCAL_ADVANTAGE,
  INTERVENTION_ZONE,
} from "@/lib/intervention-area";

export const NAV_LINKS: NavLink[] = [
  { label: "Accueil", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Zones", href: "/zones" },
  { label: "Réalisations", href: "/realisations" },
  { label: "Contact", href: "/contact" },
];

export const STATS: Stat[] = [
  { value: "5.0", label: "Etoiles google" },
  { value: "10", label: "Communes & alentours" },
  { value: "98%", label: "Taux de satisfaction" },
  { value: "24h", label: "Réponse rapide" },
];

export const SERVICES: Service[] = [
  {
    id: 1,
    icon: "🏢",
    title: "Nettoyage de bureaux",
    description: "Entretien régulier et complet de vos espaces professionnels.",
    features: [
      "Dépoussiérage & aspiration",
      "Désinfection des surfaces",
      "Nettoyage sanitaires",
      "Vidage des corbeilles",
    ],
    imageSrc: "/services/Bureau.webp",
    slug: "nettoyage-bureaux",
  },
  {
    id: 2,
    icon: "✨",
    title: "Nettoyage de vitres",
    description: "Lavage professionnel pour immeubles, bureaux et commerces.",
    features: [
      "Vitres intérieures & extérieures",
      "Façades vitrées",
      "Intervention en hauteur",
      "Résultat sans traces garanti",
    ],
    imageSrc: "/services/Vitre.webp",
    slug: "nettoyage-vitres",
  },
  {
    id: 3,
    icon: "🏗️",
    title: "Fin de chantier",
    description: "Remise en état complète après travaux.",
    features: [
      "Évacuation des gravats",
      "Dépoussiérage complet",
      "Nettoyage sols & murs",
      "Vitrages & menuiseries",
    ],
    imageSrc: "/services/Chantier.webp",
    slug: "fin-chantier",
  },
  {
    id: 4,
    icon: "🏛️",
    title: "Entretien d'immeuble",
    description: "Entretien des parties communes d'immeubles résidentiels et commerciaux.",
    features: ["Halls & couloirs", "Cages d'escalier", "Locaux poubelles", "Parkings & sous-sols"],
    imageSrc: "/services/Immeuble.webp",
    slug: "entretien-immeuble",
  },
  {
    id: 5,
    icon: "🌿",
    title: "Nettoyage de terrasse",
    description: "Entretien et nettoyage de terrasses, balcons et espaces extérieurs.",
    features: [
      "Nettoyage haute pression",
      "Traitement anti-mousse",
      "Nettoyage mobilier extérieur",
      "Évacuation des déchets",
    ],
    imageSrc: "/services/Exterieur.webp",
    slug: "nettoyage-terrasse",
  },
  {
    id: 6,
    icon: "🏠",
    title: "Nettoyage particulier",
    description: "Une solution professionnelle pour votre logement.",
    features: [
      "Nettoyage complet toutes pièces",
      "Désinfection des surfaces",
      "Nettoyage cuisine & sanitaires",
      "Intervention ponctuelle ou régulière",
    ],
    imageSrc: "/services/Particulier.webp",
    slug: "nettoyage-particulier",
  },
  {
    id: 7,
    icon: "🔑",
    title: "Nettoyage fin de bail",
    description:
      "Une solution professionnelle pour remettre en ordre votre logement et récupérer votre garantie locative.",
    features: [
      "Nettoyage complet état des lieux",
      "Détartrage & désinfection",
      "Nettoyage four, frigo & équipements",
      "Garantie récupération de caution",
    ],
    imageSrc: "/services/Bail.webp",
    slug: "nettoyage-fin-bail",
  },
  {
    id: 8,
    icon: "☀️",
    title: "Nettoyage panneaux solaires",
    description: "Entretien soigné de vos panneaux pour préserver leur rendement.",
    features: [
      "Nettoyage sans traces",
      "Méthode douce adaptée",
      "Retrait poussières & dépôts",
      "Contrôle visuel des surfaces",
    ],
    imageSrc: "/services/solar-panel-cleaning.webp",
    slug: "nettoyage-panneaux-solaires",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: "Maud Delvaux via Facebook",
    role: "",
    company: "",
    content: "Patron très à l'écoute, travail méticuleux et soigné! Je recommande vivement !",
    rating: 5,
    avatar: "/images/avatars/avatar-1.webp",
  },
  {
    id: 2,
    name: "Saelmans Jonathan via Google",
    role: "",
    company: "",
    content:
      "Service impeccable ! J’ai fait appel à Makclean pour un nettoyage et je suis entièrement satisfait du résultat. Équipe professionnelle, ponctuelle et très soigneuse. Le travail est fait avec sérieux et souci du détail, tout était parfaitement propre après leur passage. Je recommande Makclean sans hésiter pour la qualité du service et le professionnalisme. Merci encore !",
    rating: 5,
    avatar: "/images/avatars/avatar-2.webp",
  },
  {
    id: 3,
    name: "Laurent via Google",
    role: "",
    company: "",
    content:
      "Ok, j'avais promis de laisser un avis si la prestation aidait vraiment à la vente de notre maison de famille. Le nettoyage était impeccable, les détails soignés, les vitres étaient transparentes (on se comprend😉), sols brillant + odeur de frais très agréable = la maison a donné une autre image.Vendu (presque au prix) juste après la 2ème visite alors qu'il y a eu des mois de visites sans suite...Aucun regret, merci.",
    rating: 5,
    avatar: "/images/avatars/avatar-3.webp",
  },
  {
    id: 4,
    name: "C. DEPS via Google",
    role: "",
    company: "",
    content:
      "Je ne suis pas client direct, mais je travaille avec un fournisseur sur TOURNAI qui a récemment fait appel à vous. Je tenais à souligner que la différence est flagrante ! On sent tout de suite un changement de rigueur dans l'entretien des locaux et de l'accueil. C'est rare de voir une telle évolution visuelle en si peu de temps. Bravo pour votre travail qui se remarque même quand on est de passage.",
    rating: 5,
    avatar: "/images/avatars/avatar-4.webp",
  },
  {
    id: 5,
    name: "Eline Decaestecker via Google",
    role: "",
    company: "",
    content:
      "J’ai fait appel à Makclean pour le nettoyage complet d’un appartement après 7 ans d’occupation par une personne fumeuse. Je suis très satisfaite du résultat, l’appartement paraît plus lumineux, certaines pièces que je ne pensais pas récupérables (baignoire par exemple) sont à nouveau propres. L’équipe est très réactive, à l’écoute et très investie même avec des imprévus. Je recommande sans hésiter cette entreprise.",
    rating: 5,
    avatar: "/images/avatars/avatar-5.webp",
  },
];

export const SERVICES_DETAIL: ServiceDetail[] = [
  {
    slug: "nettoyage-bureaux",
    icon: "🏢",
    title: "Nettoyage de bureaux à Tournai et dans le Hainaut",
    accroche: `Makclean, basé à ${INTERVENTION_BASE_CITY}, accompagne les entreprises, PME et professions libérales de la ${INTERVENTION_AREA_LABEL} avec un nettoyage de bureaux régulier ou ponctuel, adapté à vos horaires.`,
    description: [
      "Notre objectif : vous garantir des locaux propres, sains et professionnels, tout en vous faisant gagner du temps au quotidien.",
      "Nos prestations s’adressent aux bureaux d’entreprises, PME et indépendants, cabinets médicaux et paramédicaux, agences immobilières, espaces de coworking, administrations et structures publiques. Que vous ayez un petit bureau ou un grand open space, nous adaptons nos interventions à votre réalité.",
      "Nous proposons un nettoyage complet et rigoureux de vos locaux professionnels : entretien des espaces de travail (dépoussiérage des bureaux et surfaces, nettoyage du matériel, désinfection des points de contact), entretien des sols (aspiration, lavage, moquettes), des vitres intérieures ainsi que des sanitaires et espaces cuisine.",
      "Plusieurs formules sont possibles : nettoyage quotidien, hebdomadaire, ponctuel ou après évènement. Nous intervenons tôt le matin, en journée ou en soirée pour ne pas perturber votre activité.",
      "Chez Makclean, nous utilisons des produits professionnels efficaces et des techniques adaptées à chaque type de local, en veillant à allier efficacité, hygiène et sécurité pour vos collaborateurs.",
    ],
    prestations: [
      "Dépoussiérage des bureaux, plans de travail et mobiliers",
      "Nettoyage du matériel (claviers, écrans, téléphones)",
      "Désinfection des poignées, interrupteurs et points de contact",
      "Aspiration et lavage des sols (parquet, carrelage, moquette)",
      "Nettoyage et désinfection des sanitaires",
      "Entretien des cuisines et espaces de pause",
      "Entretien des vitres intérieures et surfaces vitrées",
      "Vidage et gestion des corbeilles",
    ],
    avantages: [
      "Image professionnelle renforcée auprès de vos clients et collaborateurs",
      "Gain de temps : vous vous concentrez sur votre activité, nous gérons l’entretien",
      "Hygiène irréprochable et confort de travail amélioré pour vos équipes",
      INTERVENTION_LOCAL_ADVANTAGE,
      "Horaires flexibles (matin, journée, soirée) pour limiter les dérangements",
      "Contrats réguliers ou interventions ponctuelles selon vos besoins",
    ],
    zone: INTERVENTION_ZONE,
    imageSrc: "/services/Bureau.webp",
    ctaTitle: "Besoin d'un devis pour le nettoyage de vos bureaux ?",
  },
  {
    slug: "nettoyage-vitres",
    icon: "✨",
    title: "Nettoyage de vitres à Tournai et dans le Hainaut",
    accroche: `Spécialiste du nettoyage de vitres dans la ${INTERVENTION_AREA_LABEL}, Makclean intervient depuis ${INTERVENTION_BASE_CITY} pour bureaux, commerces, immeubles et habitations — résultat sans traces, même en hauteur.`,
    description: [
      "Makclean adapte sa méthode à chaque type de surface pour vous garantir une visibilité maximale et une image impeccable. Nous intervenons pour les vitrines de magasins, façades vitrées, bureaux, immeubles et habitations privées.",
      "Nos prestations couvrent l’ensemble des surfaces vitrées : vitres intérieures et extérieures, baies vitrées, vitrines, vérandas, verrières et châssis. Nous utilisons du matériel professionnel (raclette, mouilleur, perches télescopiques) pour un rendu sans traces.",
      "Vous pouvez opter pour un entretien ponctuel (avant événement, déménagement, vitrine encrassée) ou pour un contrat régulier mensuel ou trimestriel. Nous planifions nos passages tôt le matin, en journée ou en soirée pour ne pas déranger votre activité.",
    ],
    prestations: [
      "Vitres intérieures et extérieures",
      "Baies vitrées et portes-fenêtres",
      "Vitrines de magasins",
      "Vérandas, verrières et puits de lumière",
      "Façades vitrées et châssis",
      "Vitres en hauteur avec matériel adapté",
    ],
    avantages: [
      "Résultat sans traces ni coulures, même en plein soleil",
      "Sécurité garantie pour les surfaces en hauteur ou difficiles d'accès",
      "Image de marque renforcée pour vos bureaux, vitrines et façades",
      "Gain de temps : vous déléguez complètement l'entretien des vitres",
      INTERVENTION_LOCAL_ADVANTAGE,
      "Entretien ponctuel ou régulier selon votre activité",
    ],
    processus: [
      { number: "01", title: "Inspection", description: "Évaluation du nombre et type de vitres à nettoyer" },
      { number: "02", title: "Préparation", description: "Protection des surfaces et choix du matériel adapté" },
      { number: "03", title: "Nettoyage", description: "Lavage professionnel avec produits spécialisés" },
      { number: "04", title: "Finitions", description: "Séchage et lustrage pour un résultat impeccable" },
    ],
    frequence: "Mensuel, trimestriel ou ponctuel selon vos besoins",
    zone: INTERVENTION_ZONE,
    imageSrc: "/services/Vitre.webp",
    ctaTitle: "Besoin d'un devis pour le nettoyage de vos vitres ?",
  },
  {
    slug: "fin-chantier",
    icon: "🏗️",
    title: "Nettoyage fin de chantier à Tournai et dans le Hainaut",
    accroche: `Après des travaux, Makclean assure le nettoyage fin de chantier dans la ${INTERVENTION_AREA_LABEL} pour livrer un espace propre, sain et prêt à être occupé.`,
    description: [
      "Nous intervenons après construction neuve, rénovation complète ou partielle, aménagement de bureaux, commerces ou logements. Notre équipe est formée au nettoyage post-travaux pour transformer un chantier poussiéreux en espace prêt à vivre ou à travailler.",
      "Nos prestations couvrent le dégrossissage (évacuation des gravats et déchets), le dépoussiérage minutieux de toutes les surfaces (murs, plafonds, plinthes, portes, prises, radiateurs), le nettoyage des sols et des vitres ainsi que la suppression des traces de peinture, colle ou plâtre.",
      "Idéalement, nous intervenons juste avant la remise des clés, la mise en location ou la vente du bien. Nous planifions notre passage en fonction de votre planning de livraison pour ne pas retarder la fin de chantier.",
    ],
    prestations: [
      "Ramassage et évacuation des gravats et déchets résiduels",
      "Enlèvement des protections (adhésifs, cartons, bâches)",
      "Dépoussiérage complet des murs, plafonds, plinthes et menuiseries",
      "Nettoyage et lavage des sols (carrelage, parquet, vinyle, etc.)",
      "Détachage des traces de peinture, colle ou ciment selon les surfaces",
      "Nettoyage des vitres, châssis et encadrements",
      "Nettoyage des sanitaires, cuisines et pièces d’eau nouvellement posées",
    ],
    avantages: [
      "Équipe expérimentée en nettoyage post-travaux",
      "Matériel adapté pour aspirer les poussières fines et retirer les traces tenaces",
      "Respect des surfaces et des nouveaux revêtements",
      "Intervention rapide pour ne pas retarder la remise des clés",
      "Devis clair avant intervention et planning adapté à votre chantier",
      "Solution clé en main pour livrer un bien propre et présentable",
    ],
    processus: [
      { number: "01", title: "Visite du chantier", description: "Évaluation de l'ampleur des travaux de nettoyage" },
      { number: "02", title: "Devis détaillé", description: "Proposition tarifaire en fonction des surfaces et travaux" },
      { number: "03", title: "Gros œuvre", description: "Élimination des gravats et déchets volumineux" },
      { number: "04", title: "Finitions", description: "Nettoyage fin et lustrage pour un rendu impeccable" },
    ],
    frequence: "Intervention ponctuelle avant livraison ou remise des clés",
    zone: INTERVENTION_ZONE,
    imageSrc: "/services/Chantier.webp",
    ctaTitle: "Besoin d'un devis pour un nettoyage fin de chantier ?",
  },
  {
    slug: "entretien-immeuble",
    icon: "🏛️",
    title: "Entretien d’immeubles à Tournai et dans le Hainaut",
    accroche: `Makclean assure l'entretien régulier des parties communes d'immeubles dans la ${INTERVENTION_AREA_LABEL} — pour la satisfaction des résidents et la valorisation de votre bien.`,
    description: [
      "Nous travaillons pour des copropriétés, syndics, propriétaires privés et gestionnaires d’immeubles qui souhaitent offrir des parties communes propres, sûres et accueillantes à leurs occupants.",
      "Nos équipes interviennent selon un planning défini avec vous : nombre de passages par semaine, taches à réaliser à chaque visite, interventions ponctuelles supplémentaires (vitres, grand nettoyage…). Chaque passage est contrôlé pour garantir un résultat constant.",
      "De la petite résidence à l’immeuble de bureaux, nous proposons des contrats d’entretien sur mesure, avec un excellent rapport qualité/prix et une grande réactivité en cas de besoin particulier.",
    ],
    prestations: [
      "Nettoyage des halls d’entrée et couloirs",
      "Entretien des cages d’escaliers et paliers",
      "Nettoyage des ascenseurs et portes",
      "Nettoyage des caves, locaux vélos et locaux poubelles",
      "Balayage et nettoyage des parkings et abords",
      "Nettoyage des vitres et portes vitrées des communs",
      "Nettoyage et désinfection des sanitaires communs",
    ],
    avantages: [
      "Valorisation de votre patrimoine immobilier et meilleure première impression",
      "Satisfaction des locataires et copropriétaires grâce à des communs propres",
      "Interventions régulières planifiées et adaptées au taux d’occupation",
      "Équipe stable, identifiable et de confiance",
      "Produits adaptés aux différentes surfaces et respectueux des matériaux",
      "Suivi et ajustements possibles en fonction de l’évolution de vos besoins",
    ],
    processus: [
      { number: "01", title: "Audit des lieux", description: "Visite de l'immeuble et des parties communes" },
      { number: "02", title: "Contrat d'entretien", description: "Définition des prestations et fréquences" },
      { number: "03", title: "Planning", description: "Organisation des passages selon vos contraintes" },
      { number: "04", title: "Entretien régulier", description: "Nettoyage selon le planning établi" },
    ],
    frequence: "Hebdomadaire, bi-hebdomadaire ou quotidien selon la résidence",
    zone: INTERVENTION_ZONE,
    imageSrc: "/services/Immeuble.webp",
    ctaTitle: "Besoin d’un devis pour l’entretien de vos immeubles ?",
  },
  {
    slug: "nettoyage-terrasse",
    icon: "🌿",
    title: "Nettoyage de terrasse à Tournai et dans le Hainaut",
    accroche: `Terrasse encrassée ou glissante ? Makclean redonne éclat et sécurité à vos espaces extérieurs dans la ${INTERVENTION_AREA_LABEL}.`,
    description: [
      "Nous intervenons sur les terrasses, balcons, allées et zones extérieures pour retirer la saleté incrustée, les taches noires, la mousse et les algues. Résultat : une terrasse plus propre, plus belle et surtout beaucoup moins glissante.",
      "Nous utilisons du matériel haute pression professionnel ainsi que des produits spécifiquement adaptés à votre revêtement (carrelage, pierre naturelle, béton, pavés…). L’objectif : nettoyer en profondeur sans abîmer les surfaces.",
      "En fin d’intervention, nous pouvons appliquer un traitement anti-mousse préventif afin de ralentir la réapparition des verdissures et de prolonger la durée du résultat.",
    ],
    prestations: [
      "Nettoyage haute pression des terrasses en carrelage, pierre naturelle ou béton",
      "Nettoyage des balcons, allées et espaces extérieurs",
      "Élimination de la mousse, des algues et des saletés incrustées",
      "Nettoyage des joints et des interstices",
      "Nettoyage des meubles de jardin et accessoires extérieurs",
      "Application d’un traitement anti-mousse préventif (sur demande)",
    ],
    avantages: [
      "Matériel professionnel haute pression pour un résultat visible immédiatement",
      "Respect des revêtements grâce à des réglages et produits adaptés",
      "Terrasse plus sûre, moins glissante et plus agréable à utiliser",
      "Service ponctuel ou saisonnier (printemps/automne) selon vos besoins",
      "Possibilité de traitement préventif contre la mousse",
      INTERVENTION_LOCAL_ADVANTAGE,
    ],
    processus: [
      {
        number: "01",
        title: "Évaluation",
        description: "Inspection de votre terrasse et identification des besoins spécifiques",
      },
      {
        number: "02",
        title: "Préparation",
        description: "Protection des végétaux et choix des produits adaptés",
      },
      {
        number: "03",
        title: "Nettoyage",
        description: "Nettoyage haute pression et traitement des surfaces",
      },
      {
        number: "04",
        title: "Finitions",
        description: "Rinçage et traitement préventif pour un résultat durable",
      },
    ],
    frequence: "Saisonnier (printemps/automne) ou ponctuel selon vos besoins",
    zone: INTERVENTION_ZONE,
    imageSrc: "/services/Exterieur.webp",
    ctaTitle: "Besoin d'un devis pour le nettoyage de votre terrasse ?",
  },
  {
    slug: "nettoyage-particulier",
    icon: "🏠",
    title: "Nettoyage pour particuliers à Tournai et dans le Hainaut",
    accroche: `Manque de temps pour entretenir votre logement ? Makclean propose un nettoyage pour particuliers dans la ${INTERVENTION_AREA_LABEL}, adapté à votre rythme de vie.`,
    description: [
      "Profitez d’un intérieur propre et agréable sans sacrifier vos soirées ou vos week-ends. Nous intervenons à la fréquence de votre choix pour l’entretien complet de votre logement.",
      "Notre équipe de confiance intervient avec discrétion et professionnalisme à votre domicile. Nous nous adaptons à vos priorités : pièces à traiter, tâches spécifiques, jours et horaires d’intervention.",
      "Sur demande, nous pouvons utiliser des produits plus écologiques pour un nettoyage respectueux de votre famille, de vos animaux et de l’environnement.",
    ],
    prestations: [
      "Pièces à vivre (salon, salle à manger)",
      "Chambres",
      "Cuisine (plans de travail, électroménager)",
      "Salles de bain et sanitaires",
      "Sols (aspirateur, lavage)",
      "Dépoussiérage des meubles",
      "Vitres intérieures",
    ],
    avantages: [
      "Plus de temps pour vous et votre famille",
      "Service personnalisé selon vos priorités",
      "Flexibilité horaire",
      "Équipe de confiance et discrète",
      "Produits écologiques sur demande",
      "Tarifs transparents",
    ],
    processus: [
      { number: "01", title: "Premier contact", description: "Échange sur vos besoins et attentes" },
      { number: "02", title: "Devis personnalisé", description: "Proposition adaptée à votre logement" },
      { number: "03", title: "Premier passage", description: "Nettoyage complet de votre domicile" },
      { number: "04", title: "Entretien régulier", description: "Passages planifiés selon votre convenance" },
    ],
    frequence: "Hebdomadaire, bi-mensuel ou ponctuel",
    zone: INTERVENTION_ZONE,
    imageSrc: "/services/Particulier.webp",
    ctaTitle: "Envie d’un domicile propre sans effort ? Demandez votre devis.",
  },
  {
    slug: "nettoyage-fin-bail",
    icon: "🔑",
    title: "Nettoyage fin de bail à Tournai et dans le Hainaut",
    accroche:
      "Le nettoyage fin de bail est essentiel pour récupérer votre garantie locative. Makclean prend en charge la remise en état complète de votre logement dans la région de Tournai et du Hainaut, avant l’état des lieux de sortie.",
    description: [
      "Nous connaissons les attentes des propriétaires, agences et états des lieux. Chaque pièce est traitée avec soin pour présenter un logement propre, rangé et prêt à être contrôlé.",
      "Nos équipes s’occupent de la cuisine, des sanitaires, des sols, des vitres, des placards et des petits détails qui font souvent l’objet de remarques lors de l’état des lieux.",
      "Sur demande, nous pouvons fournir un certificat de nettoyage à présenter à votre propriétaire ou à l’agence immobilière.",
    ],
    prestations: [
      "Cuisine complète (four, hotte, plaques, réfrigérateur, placards)",
      "Salle de bain et WC (détartrage, joints, robinetterie)",
      "Toutes les pièces (sols, plinthes, radiateurs)",
      "Fenêtres intérieures et extérieures",
      "Portes, poignées et interrupteurs",
      "Placards et dressings (intérieur et extérieur)",
      "Balcon ou terrasse",
      "Cave et garage (sur demande)",
    ],
    avantages: [
      "Récupération de votre garantie locative",
      "État des lieux sans remarque",
      "Intervention rapide avant remise des clés",
      "Nettoyage conforme aux exigences des propriétaires",
      "Devis gratuit et transparent",
      "Certificat de nettoyage sur demande",
      "Disponible 7j/7 pour les urgences",
    ],
    processus: [
      {
        number: "01",
        title: "Évaluation gratuite",
        description:
          "Visite du logement pour établir un devis précis selon l'état et la surface",
      },
      {
        number: "02",
        title: "Planification",
        description: "Intervention planifiée selon la date de votre état des lieux de sortie",
      },
      {
        number: "03",
        title: "Nettoyage complet",
        description: "Remise en état intégrale du logement par notre équipe",
      },
      {
        number: "04",
        title: "Contrôle final",
        description: "Vérification point par point avant votre état des lieux",
      },
    ],
    frequence: "Intervention ponctuelle avant état des lieux",
    zone: INTERVENTION_ZONE,
    imageSrc: "/services/Bail.webp",
    ctaTitle: "Besoin d’un nettoyage fin de bail avant votre état des lieux ?",
  },
  {
    slug: "nettoyage-panneaux-solaires",
    icon: "☀️",
    title: "Nettoyage de panneaux solaires à Tournai et dans le Hainaut",
    accroche: `Panneaux solaires ternis par la poussière, le pollen ou les dépôts verts ? Makclean les nettoie avec soin dans la ${INTERVENTION_AREA_LABEL} pour préserver leur rendement.`,
    description: [
      "Des panneaux solaires encrassés captent moins bien la lumière. Un entretien adapté permet de retirer les salissures accumulées sans agresser les surfaces ni les joints.",
      "Makclean intervient avec une méthode douce, pensée pour les installations résidentielles et professionnelles : nettoyage régulier ou ponctuel, après une période de pollen, de poussières, de travaux ou de fortes intempéries.",
      "Nous prenons le temps d'observer l'état général des panneaux avant et après l'intervention. L'objectif est simple : rendre les surfaces propres, limiter les traces et vous aider à conserver une installation performante dans la durée.",
    ],
    prestations: [
      "Nettoyage de panneaux photovoltaïques résidentiels",
      "Nettoyage de panneaux solaires sur bâtiments professionnels",
      "Retrait des poussières, pollens et dépôts atmosphériques",
      "Nettoyage des fientes d'oiseaux et salissures incrustées",
      "Rinçage soigné pour limiter les traces",
      "Contrôle visuel de l'état des surfaces accessibles",
      "Intervention ponctuelle ou entretien saisonnier",
      "Nettoyage possible en complément des vitres ou extérieurs",
    ],
    avantages: [
      "Préserve le rendement de vos panneaux solaires",
      "Méthode douce adaptée aux surfaces photovoltaïques",
      "Résultat propre sans produit agressif inutile",
      INTERVENTION_LOCAL_ADVANTAGE,
      "Idéal après pollen, poussières, travaux ou intempéries",
      "Devis clair avant intervention",
    ],
    processus: [
      {
        number: "01",
        title: "Échange sur l'installation",
        description:
          "Localisation, accessibilité, type de toiture ou support et niveau d'encrassement",
      },
      {
        number: "02",
        title: "Devis et planning",
        description: "Proposition adaptée à la configuration et aux contraintes du site",
      },
      {
        number: "03",
        title: "Nettoyage doux",
        description: "Retrait des salissures avec une méthode respectueuse des panneaux",
      },
      {
        number: "04",
        title: "Contrôle final",
        description:
          "Vérification visuelle du résultat et conseils d'entretien si nécessaire",
      },
    ],
    frequence: "1 à 2 fois par an selon l'exposition, les arbres, les poussières et les intempéries",
    zone: INTERVENTION_ZONE,
    imageSrc: "/services/solar-panel-cleaning.webp",
    ctaTitle: "Besoin d’un nettoyage pour vos panneaux solaires ?",
  },
];
